config/routes.rb
Rails.application.routes.draw do
  resources :yourtours

  resources :tourisms

  resources :ats

  resources :addtravels

  resources :cultures

  root 'articles#index'
  post '/aaa' => 'profiles#aaa'
  post '/live' => 'wildlives#live'
  post '/authenticate' => 'articles#authenticate'
  post '/almora' => 'birds#almora'
  post '/au' => 'registers#au'
  post '/abc' => 'cycles#abc'
  post '/authh' => 'trekkings#authh'
  post '/contactus' => 'articles#contactus'
  get 'articles/home' =>'articles#home'
  get 'articles/logout' =>'articles#logout',:as=>"logout"
  get 'cultures/index' =>'cultures#index'
  get 'articles/contact' => 'articles#contact', :as=>"contact"
  get 'registers/index' =>'registers#index'
  get 'birds/index' =>'birds#index'
  get 'abouts/index' =>'abouts#index'
  get 'wildlives/index' =>'wildlives#index'
  get 'birds/show' =>'birds#show'
  get 'hotels/index' =>'hotels#index'
  get 'trekkings/index' => 'trekkings#index'
  get 'birds/trekkings/index' => 'trekkings#index'
  get 'birds/trekkings/birds/show' => 'birds#show'
  get 'profiles/index' =>'profiles#index'
  get 'maps/index' =>'maps#index'
  get 'abouts/ae' =>'abouts#ae'
  post '/ae' => 'articles#ae'
  get 'cycles/index' => 'cycles#index'

 end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/addtravel.rb
class Addtravel < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates_presence_of :email
	validates_presence_of :password
	has_one :profile

end

app/models/at.rb
class At < ActiveRecord::Base
end

app/models/bird.rb
class Bird < ActiveRecord::Base
end

app/models/culture.rb
class Culture < ActiveRecord::Base
end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
end

app/models/map.rb
class Map < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :article
end

app/models/register.rb
class Register < ActiveRecord::Base
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/tourism.rb
class Tourism < ActiveRecord::Base
end

app/models/trekking.rb
class Trekking < ActiveRecord::Base
end

app/models/wildlife.rb
class Wildlife < ActiveRecord::Base
end

app/models/yourtour.rb
class Yourtour < ActiveRecord::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter  :check_login , :except=>[:index, :authenticate, :contactus, :contact]
	def index

end

	def authenticate
		em=params[:email]
		ps=params[:password]
		if em.blank?
			flash[:error]="email required"
			redirect_to :action=>"index"
		else
			valid_user=Article.where(:email=>em, :password=>ps).first
			
			if valid_user
				session[:id]=valid_user.id
				redirect_to :action=> "home"
			else
				flash[:error]="invalid username or password"
				redirect_to :action=>"index"
			end
		end
	end

	def home
		id = session[:id]
		@art = Article.find(id)
	end

	def logout
		session[:id] = nil
		flash[:error]="Successfully Logged Out"
				redirect_to :action=>"index"
	end

	def send_mail_to_friend
		Notifier.send_email(params[:name], params[:email].deliver)
		flash[:notice]='mail send'
		redirect_to :action => 'index'
	end


  def contact

  end

  def contactus
    Notifier.send_email(params[:email]).deliver
    flash[:notice] = "mail sent successfully"
    redirect_to :action => "index"
  end

protected
def set_i18n_locale_from_params
if params[:locale]
if I18n.available_locales.include?(params[:locale].to_sym)
I18n.locale = params[:locale]
else
flash.now[:notice] =
"#{params[:locale]} translation not available"
logger.error flash.now[:notice]
end
end
end
def default_url_options
{ :locale => I18n.locale }
end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/ats_helper.rb
module AtsHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/authenticate.html.erb
<%= flash[:error]  %>

app/views/articles/contact.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mf</title>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
 
</head>
<body  id="page" >             
   

    <div id="mi" class="bgParallax" data-speed="35">
      <article>
      <h1 style="font-family:algerian;">SCROLL DOWN TO CONTACT</h1>
        <p>This is our online portal for QUERIES. Get ready for your secure, safe and most enjoyble tours. We provide you the best quality services. </p>

        <p>HIGH ADVENTURE UTTARAKHAND</p>


        <p>www.trekking himlayas.in <br>
        phone: +91-7508503094<br>
        +91-7508504091</p>

        <%= flash[:error]  %>
        <%= form_tag :action=>"contactus" do %>
        <div class="field">
         Username
        <%= text_field_tag :email %>
        </div>
        <input type = "submit" name="sub" value="send email">
 
<% end %>
       </article>
  </div>
</body></html>

app/views/articles/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mf</title>
</head>
<body> 
<br><br>

<div id="m" class="bgx" data-speed="15">
      <article>
      <h1 style="font-family:algerian;font-size:69px"><br> WELCOME TO YOUR DREAM TRIP </h1>
        <p>

<%= link_to "contact us", "articles/contact" %>
<%= session[:id] %>
<%= @art.email %>

<%= link_to "contact",  contact_path %>

<%= link_to "Logout",  logout_path %>
</p>
        
       </article>
  </div>
  <div id="aboutus" class="bgParallax" data-speed="10">
       <article>
       <b> <h1>LETS TRAVEL: ITENARY</h1>
       <p><br>Day0: Departure from old Delhi railway station [10 .40 P.M.] to Kathgodam via Ranikhet exp [25013] <br><br>Day1: Arrival at Kathgodam railway station, then drive to Jalna Elphinstone Himalayan Resort. It is a Himalayan facing resort  designed for  lovers of Nature. After noon a small trek to Banardevi and enjoy the beautiful view of Almora city then back to resort for camp fair & dinner.<br><br>
      Day2: After breakfast trek to nearby Kumaoni  village to see local culture and routine life of local people and birds around settlement, back to  camp for night stay.<br><br>
      Day3: After breakfast 18 k.m.trek  to Almora enjoy the oldest khagmara temple made by katuari  kings, then drive to Binsar. It was the summer capital of chand kings. The region is now under the Binsar Sanctuary at least more then 200 identified bird species in the region. You can enjoy the 300 k.m. panoramic Himalayan view include Nandadevi peak [ 7600mtrs.] Check in the T.R.H. Binsar for night stay.<br><br>
      Day 4: After breakfast, trek 17 k.m. to Jageshwar.. It is a pilgrim town. The temples were built by rulers of Kumaon between the 8th century to the 16th century. Check in the T.R.H. Jageshwar.<br><br>
      Day5: After breakfast drive to Kanchi, then trek 12 kms.to Nainital ( old British trail)  Check in the fair light trails, enjoy the full lake view at your place.<br><br>
      Day6: After breakfast, 12 k.m. trek to Vinayak. One of the most beautiful trek with soft cool air, shades of tall trees, songs of birds, beauty of snow mountains etc. over night stay in camp.<br><br>
      Day7: After breakfast back to the fair light trail for lunch. Evening  explore the mall then back and  enjoy dinner and camp fire.<br><br>
      Day8: After breakfast  departure to Delhi.<br><br>


       </p></article><br><br></div>


       <div id="m" class="bgx" data-speed="10">
       <article>
        <h1>Water</h1>
       <p>You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man. </p>
      </article><br></div>
</body>
</html>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mf</title>
 
</head>
<body id="page"> 
 

<div class="row-bot">

        <div class="row-bot-bg">

     <h3>&nbsp;&nbsp;book hotels tours and trips in any season for secure and wondersome experiences</h3>
     <br>


<div class="slider-wrapper">
          <ul class="slides">
              <input type="radio" name="radio-btn" id="img-1" checked />
              <li class="slide-container">
              <div class="slide">
              <%= image_tag("bgs.jpg", :alt => "Travel and tours") %>
                  </div>
              <div class="nav">
                <label for="img-6" class="prev">&#x2039;</label>
                <label for="img-2" class="next">&#x203a;</label>
              </div>
              </li>

              <input type="radio" name="radio-btn" id="img-2" />
              <li class="slide-container">
                  <div class="slide">
          <%= image_tag("camp.jpg", :alt => "Travel and tours") %>
                  </div>
              <div class="nav">
                <label for="img-1" class="prev">&#x2039;</label>
                <label for="img-3" class="next">&#x203a;</label>
              </div>
              </li>

              <input type="radio" name="radio-btn" id="img-3" />
              <li class="slide-container">
                  <div class="slide">
          <%= image_tag("front.jpg", :alt => "Travel and tours") %>
                  </div>
              <div class="nav">
                <label for="img-2" class="prev">&#x2039;</label>
                <label for="img-4" class="next">&#x203a;</label>
              </div>
              </li>

            
              <input type="radio" name="radio-btn" id="img-4" />
              <li class="slide-container">
                  <div class="slide">
          <%= image_tag("rhodo.jpg", :alt => "Travel and tours") %>
                  </div>
              <div class="nav">
                <label for="img-4" class="prev">&#x2039;</label>
                <label for="img-6" class="next">&#x203a;</label>
              </div>
              </li>

              <input type="radio" name="radio-btn" id="img-6" />
              <li class="slide-container">
                  <div class="slide">
          <%= image_tag("img.jpg", :alt => "Travel and tours") %>
                  </div>
              <div class="nav">
                <label for="img-5" class="prev">&#x2039;</label>
                <label for="img-1" class="next">&#x203a;</label>
              </div>
              </li>
          </ul>
          <li class="nav-dots">
                <label for="img-1" class="nav-dot" id="img-dot-1"></label>
                <label for="img-2" class="nav-dot" id="img-dot-2"></label>
                <label for="img-3" class="nav-dot" id="img-dot-3"></label>
                <label for="img-5" class="nav-dot" id="img-dot-4"></label>
                <label for="img-6" class="nav-dot" id="img-dot-6"></label>
              </li>
        </div></div></div>
  <br>

<table width="1345" >
  <tr>
    <td><a href="#"><H2><b style="font-family:algerian;">&nbsp;KAUSANI BIRD CAMP</b></H2>Especial 4Night 5Days luxuary trip<br>CLICK HERE FOR MORE DETAILS</a></td>
    <td><a href="#"><H2><b style="font-family:algerian;">&nbsp;RHODODENDRON TOUR</b></H2>Especial 4Night 5Days luxuary trip<br>CLICK HERE FOR MORE DETAILS</a></td>
    <td><a href="#"><H2><b style="font-family:algerian;">&nbsp;INDIAN CAMP</b></H2>Especial 4Night 5Days luxuary trip<br>CLICK HERE FOR MORE DETAILS</a></td>
    <td><a href="#"><H2><b style="font-family:algerian;">&nbsp;JUNGLE CAMP</b></H2>Especial 4Night 5Days luxuary trip<br>CLICK HERE FOR MORE DETAILS</a></td>
  </tr>
<tr>

    <td class="bird"></td>
    <td class="rho" ></td>
    <td class="butter"></td>
    <td class="kafal"></td>
  </tr>
<br><br><br>
  <tr>
    <td><a href="birds/index" class="div red shield">BOOK NOW<br><br><h1>$120/-</h1> only</a></td>
    <td><a href="wildlives/index" class="div red shield">BOOK NOW<br><br><h1>$120/-</h1> only</a></td>
    <td><a href="trekkings/index" class="div red shield">BOOK NOW<br><br><h1>$120/-</h1> only</a></td>
    <td><a href="cycles/index" class="div red shield">BOOK NOW<br><br><h1>$120/-</h1> only</a></td>
  </tr>

 </table>

<br><br><br>
        <section id="content">
          <div class="main">
    <div class="wrapper">
      <article class="column-1">
        <div class="indent-left">
          <div class="maxheight indent-bot">
            <h3>Our Services</h3>
            <ul class="list-1">

                    <%= link_to "contact us", "articles/contact" %>

              <li><a href="#">WINTER CAMP</a></li>
              <li><a href="#">CYCLING TRIP </a></li>
              <li><a href="#">TREK THE SNOW</a></li>
              <li><a href="#">OFFBEAT TOURS</a></li>
              <li><a href="#">LEISURE TRIPS</a></li>
              <li><a href="#">ADD YOUR OWN TRIP</a></li>
              <li><a href="#">CONTACT INFORMATION</a></li>
            </ul>
          </div>
      </article>
      <article class="column-2">
        

    </div>
  </div>
</section>


</body>
</html>

