config/routes.rb
Rails.application.routes.draw do
  resources :yourtours

  resources :tourisms

  resources :ats

  resources :addtravels

  resources :cultures

  root 'articles#index'
  post '/aaa' => 'profiles#aaa'
  post '/live' => 'wildlives#live'
  post '/authenticate' => 'articles#authenticate'
  post '/almora' => 'birds#almora'
  post '/au' => 'registers#au'
  post '/abc' => 'cycles#abc'
  post '/authh' => 'trekkings#authh'
  post '/contactus' => 'articles#contactus'
  get 'articles/home' =>'articles#home'
  get 'articles/logout' =>'articles#logout',:as=>"logout"
  get 'cultures/index' =>'cultures#index'
  get 'articles/contact' => 'articles#contact', :as=>"contact"
  get 'registers/index' =>'registers#index'
  get 'birds/index' =>'birds#index'
  get 'abouts/index' =>'abouts#index'
  get 'wildlives/index' =>'wildlives#index'
  get 'birds/show' =>'birds#show'
  get 'hotels/index' =>'hotels#index'
  get 'trekkings/index' => 'trekkings#index'
  get 'birds/trekkings/index' => 'trekkings#index'
  get 'birds/trekkings/birds/show' => 'birds#show'
  get 'profiles/index' =>'profiles#index'
  get 'maps/index' =>'maps#index'
  get 'abouts/ae' =>'abouts#ae'
  post '/ae' => 'articles#ae'
  get 'cycles/index' => 'cycles#index'

 end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/addtravel.rb
class Addtravel < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates_presence_of :email
	validates_presence_of :password
	has_one :profile

end

app/models/at.rb
class At < ActiveRecord::Base
end

app/models/bird.rb
class Bird < ActiveRecord::Base
end

app/models/culture.rb
class Culture < ActiveRecord::Base
end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
end

app/models/map.rb
class Map < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :article
end

app/models/register.rb
class Register < ActiveRecord::Base
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/tourism.rb
class Tourism < ActiveRecord::Base
end

app/models/trekking.rb
class Trekking < ActiveRecord::Base
end

app/models/wildlife.rb
class Wildlife < ActiveRecord::Base
end

app/models/yourtour.rb
class Yourtour < ActiveRecord::Base
end

app/controllers/ats_controller.rb
class AtsController < ApplicationController
  before_action :set_at, only: [:show, :edit, :update, :destroy]

  # GET /ats
  # GET /ats.json
  def index
    @ats = At.all
  end

  # GET /ats/1
  # GET /ats/1.json
  def show
  end

  # GET /ats/new
  def new
    @at = At.new
  end

  # GET /ats/1/edit
  def edit
  end

  # POST /ats
  # POST /ats.json
  def create
    @at = At.new(at_params)

    respond_to do |format|
      if @at.save
        format.html { redirect_to @at, notice: 'At was successfully created.' }
        format.json { render :show, status: :created, location: @at }
      else
        format.html { render :new }
        format.json { render json: @at.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ats/1
  # PATCH/PUT /ats/1.json
  def update
    respond_to do |format|
      if @at.update(at_params)
        format.html { redirect_to @at, notice: 'At was successfully updated.' }
        format.json { render :show, status: :ok, location: @at }
      else
        format.html { render :edit }
        format.json { render json: @at.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ats/1
  # DELETE /ats/1.json
  def destroy
    @at.destroy
    respond_to do |format|
      format.html { redirect_to ats_url, notice: 'At was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_at
      @at = At.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def at_params
      params.require(:at).permit(:string, :string)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/ats_helper.rb
module AtsHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ats/_form.html.erb
<%= form_for(@at) do |f| %>
  <% if @at.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@at.errors.count, "error") %> prohibited this at from being saved:</h2>

      <ul>
      <% @at.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ats/edit.html.erb
<h1>Editing at</h1>

<%= render 'form' %>

<%= link_to 'Show', @at %> |
<%= link_to 'Back', ats_path %>

app/views/ats/index.html.erb
<h1>Listing ats</h1>

<table>
  <thead>
    <tr>
      <th>String</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ats.each do |at| %>
      <tr>
        <td><%= at.string %></td>
        <td><%= at.string %></td>
        <td><%= link_to 'Show', at %></td>
        <td><%= link_to 'Edit', edit_at_path(at) %></td>
        <td><%= link_to 'Destroy', at, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New At', new_at_path %>

app/views/ats/new.html.erb
<h1>New at</h1>

<%= render 'form' %>

<%= link_to 'Back', ats_path %>

app/views/ats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>String:</strong>
  <%= @at.string %>
</p>



<%= link_to 'Edit', edit_at_path(@at) %> |
<%= link_to 'Back', ats_path %>